version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: roamctl
    main: ./cmd/roamctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
      - amd64
      - arm
    goarm: ["7"]

  - id: roamctl-tui
    binary: roamctl-tui
    main: ./cmd/roamctl-tui
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
      - amd64
      - arm
    goarm: ["7"]

archives:
  - id: roamctl
    ids: [roamctl]
    formats: [tar.gz]
    name_template: >-
      roamctl_
      {{- .Arch }}
  - id: roamctl-tui
    ids: [roamctl-tui]
    formats: [tar.gz]
    name_template: >-
      roamctl-tui_
      {{- .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
